# Generated by Django 5.1.6 on 2025-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_producer_last_login_recycler_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
