# Generated by Django 5.1.6 on 2025-03-08 19:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_producer_company_logo_alter_producer_pcb_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='pcb_doc',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='pcb_doc',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
