# Generated by Django 5.1.6 on 2025-03-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_producer_pcb_doc_alter_recycler_pcb_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
