# Generated by Django 5.1.6 on 2025-03-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_producer_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producer',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recycler',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
