# Generated by Django 5.1.6 on 2025-03-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_populate_unique_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='unique_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='unique_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
