# Generated by Django 5.1.6 on 2025-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_producer_unique_id_alter_recycler_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
