# Generated by Django 5.1.6 on 2025-03-15 14:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="SuperAdmin's email address", max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(help_text='Hashed password for the SuperAdmin', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SuperAdmin',
                'verbose_name_plural': 'SuperAdmins',
            },
        ),
    ]
