# Generated by Django 5.1.6 on 2025-03-30 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction fee applied to transactions (fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.CharField(blank=True, help_text='Optional description of the fee', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Fee',
                'verbose_name_plural': 'Transaction Fees',
            },
        ),
    ]
