# Generated by Django 5.1.6 on 2025-05-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_transactionfee_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfee',
            name='transaction_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
