# Generated by Django 5.1.6 on 2025-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_transactionfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfee',
            name='transaction_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
