# Generated by Django 5.1.6 on 2025-03-06 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_producer_address_producer_city_producer_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerEPR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('epr_registration_date', models.DateField()),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('producer_type', models.CharField(max_length=100)),
                ('epr_certificate', models.FileField(upload_to='certificates/')),
                ('gst_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='users.producer')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclerEPR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50, unique=True)),
                ('epr_registration_date', models.DateField()),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('recycler_type', models.CharField(max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('epr_certificate', models.FileField(upload_to='certificates/')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='users.recycler')),
            ],
        ),
    ]
