# Generated by Django 5.1.6 on 2025-04-24 14:21

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import epr_account.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPRCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('product_type', models.CharField()),
                ('credit_type', models.CharField()),
                ('year', models.DateTimeField()),
                ('processing_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comulative_certificate_potential', models.FloatField()),
                ('available_certificate_value', models.FloatField()),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_epr_credits', to='users.recycler')),
            ],
        ),
        migrations.CreateModel(
            name='CreditOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=True)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('FY', models.IntegerField(default=epr_account.models.get_default_year)),
                ('offer_title', models.CharField(default='Default Offer', max_length=255)),
                ('credit_available', models.FloatField(default=0.0)),
                ('minimum_purchase', models.FloatField(default=0.0)),
                ('price_per_credit', models.FloatField(default=0.0)),
                ('product_image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('availability_proof', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('credit_type', models.CharField()),
                ('product_type', models.CharField()),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trail_documents', models.JSONField(default=epr_account.models.get_default_supporting_docs, validators=[epr_account.models.validate_doc_choices])),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_credit_offers', to='users.recycler')),
                ('epr_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_credit_offers', to='epr_account.eprcredit')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerEPR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50, unique=True)),
                ('epr_registration_date', models.DateField()),
                ('epr_registered_name', models.CharField(max_length=100)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('producer_type', models.CharField()),
                ('epr_certificate', epr_account.models.CustomCloudinaryField(max_length=255, verbose_name='file')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('label', models.CharField(default='EPR Account', max_length=100)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='users.producer')),
            ],
        ),
        migrations.CreateModel(
            name='EPRTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('product_type', models.CharField()),
                ('credit_type', models.CharField()),
                ('FY', models.IntegerField()),
                ('target_quantity', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('achieved_quantity', models.IntegerField(default=0)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_epr_targets', to='users.producer')),
                ('epr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_targets', to='epr_account.producerepr')),
            ],
        ),
        migrations.CreateModel(
            name='CounterCreditOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('FY', models.IntegerField(default=epr_account.models.get_default_year)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_counter_credit_offer', to='users.producer')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_counter_credit_offers', to='users.recycler')),
                ('credit_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_credit_offers', to='epr_account.creditoffer')),
                ('producer_epr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_credit_offers', to='epr_account.producerepr')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasesRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FY', models.IntegerField(default=epr_account.models.get_default_year)),
                ('quantity', models.FloatField(default=0.0)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='epr_account.creditoffer')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_producer_transactions', to='users.producer')),
                ('producer_epr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_epr_transactions', to='epr_account.producerepr')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_recycler_transactions', to='users.recycler')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclerEPR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50, unique=True)),
                ('epr_registration_date', models.DateField()),
                ('epr_registered_name', models.CharField()),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('recycler_type', models.CharField()),
                ('epr_certificate', epr_account.models.CustomCloudinaryField(max_length=255, verbose_name='file')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('label', models.CharField(default='EPR Account', max_length=100)),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='users.recycler')),
            ],
        ),
        migrations.AddField(
            model_name='eprcredit',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_credits', to='epr_account.recyclerepr'),
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_credit_offers', to='epr_account.recyclerepr'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(editable=False, max_length=8, unique=True)),
                ('total_price', models.FloatField()),
                ('credit_type', models.CharField()),
                ('waste_type', models.CharField(max_length=20)),
                ('recycler_type', models.CharField()),
                ('price_per_credit', models.FloatField()),
                ('product_type', models.CharField()),
                ('producer_type', models.CharField()),
                ('credit_quantity', models.FloatField()),
                ('offered_by', models.CharField(max_length=20)),
                ('work_order_date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('transaction_proof', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='transaction_proof')),
                ('producer_transfer_proof', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='producer_transfer_proof')),
                ('trail_documents', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='trail_documents')),
                ('recycler_transfer_proof', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='recycler_transfer_proof')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counter_credit_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epr_account.countercreditoffer')),
                ('credit_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epr_account.creditoffer')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_transactions', to='users.producer')),
                ('producer_epr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epr_transactions', to='epr_account.producerepr')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_transactions', to='users.recycler')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_types', to='epr_account.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='epr_account.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_types', to='epr_account.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_types', to='epr_account.wastetype')),
            ],
        ),
    ]
