# Generated by Django 5.1.6 on 2025-03-07 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0001_initial'),
        ('users', '0002_producer_address_producer_city_producer_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclerepr',
            name='credit_type',
        ),
        migrations.RemoveField(
            model_name='recyclerepr',
            name='product_type',
        ),
        migrations.CreateModel(
            name='EPRCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50, unique=True)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('product_type', models.CharField(max_length=100)),
                ('credit_type', models.CharField(max_length=100)),
                ('year', models.DateTimeField()),
                ('processing_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comulative_certificate_potential', models.CharField(max_length=250)),
                ('available_certificate_value', models.CharField(max_length=250)),
                ('epr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='epr_account.recyclerepr')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyler', to='users.recycler')),
            ],
        ),
    ]
