# Generated by Django 5.1.6 on 2025-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerepr',
            name='label',
        ),
        migrations.RemoveField(
            model_name='recyclerepr',
            name='label',
        ),
    ]
