# Generated by Django 5.1.6 on 2025-06-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epr_account', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countercreditoffer',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_counter_credit_offer', to='users.producer'),
        ),
        migrations.AddField(
            model_name='countercreditoffer',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_counter_credit_offers', to='users.recycler'),
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_credit_offers', to='users.recycler'),
        ),
        migrations.AddField(
            model_name='countercreditoffer',
            name='credit_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_credit_offers', to='epr_account.creditoffer'),
        ),
        migrations.AddField(
            model_name='eprcredit',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_epr_credits', to='users.recycler'),
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='epr_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_credit_offers', to='epr_account.eprcredit'),
        ),
        migrations.AddField(
            model_name='eprtarget',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_epr_targets', to='users.producer'),
        ),
        migrations.AddField(
            model_name='producerepr',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='users.producer'),
        ),
        migrations.AddField(
            model_name='eprtarget',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_targets', to='epr_account.producerepr'),
        ),
        migrations.AddField(
            model_name='countercreditoffer',
            name='producer_epr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_credit_offers', to='epr_account.producerepr'),
        ),
        migrations.AddField(
            model_name='purchasesrequest',
            name='credit_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='epr_account.creditoffer'),
        ),
        migrations.AddField(
            model_name='purchasesrequest',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_producer_transactions', to='users.producer'),
        ),
        migrations.AddField(
            model_name='purchasesrequest',
            name='producer_epr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_epr_transactions', to='epr_account.producerepr'),
        ),
        migrations.AddField(
            model_name='purchasesrequest',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_recycler_transactions', to='users.recycler'),
        ),
        migrations.AddField(
            model_name='recyclerepr',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='users.recycler'),
        ),
        migrations.AddField(
            model_name='eprcredit',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_credits', to='epr_account.recyclerepr'),
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_credit_offers', to='epr_account.recyclerepr'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counter_credit_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epr_account.countercreditoffer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='epr_account.creditoffer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='epr_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epr_account.eprtarget'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_transactions', to='users.producer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='producer_epr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epr_transactions', to='epr_account.producerepr'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_transactions', to='users.recycler'),
        ),
        migrations.AddField(
            model_name='recyclertype',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_types', to='epr_account.wastetype'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='epr_account.wastetype'),
        ),
        migrations.AddField(
            model_name='producertype',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_types', to='epr_account.wastetype'),
        ),
        migrations.AddField(
            model_name='credittype',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_types', to='epr_account.wastetype'),
        ),
    ]
