# Generated by Django 5.1.6 on 2025-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0002_remove_producerepr_label_remove_recyclerepr_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerepr',
            name='label',
            field=models.CharField(default='EPR Account', max_length=100),
        ),
        migrations.AddField(
            model_name='recyclerepr',
            name='label',
            field=models.CharField(default='EPR Account', max_length=100),
        ),
    ]
