# Generated by Django 5.1.6 on 2025-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0002_remove_recyclerepr_credit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprcredit',
            name='epr_registration_number',
            field=models.CharField(max_length=50),
        ),
    ]
