# Generated by Django 5.1.6 on 2025-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transac_id',
            field=models.CharField(default=None, editable=False, max_length=8, unique=True),
        ),
    ]
