# Generated by Django 5.1.6 on 2025-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0003_transaction_transac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='countercreditoffer',
            name='order_id',
            field=models.CharField(default=None, editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='purchasesrequest',
            name='order_id',
            field=models.CharField(default=None, editable=False, max_length=8, unique=True),
        ),
    ]
