# Generated by Django 5.1.6 on 2025-03-07 18:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0003_alter_eprcredit_epr_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerepr',
            name='epr_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='recyclerepr',
            name='epr_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
