# Generated by Django 5.1.6 on 2025-04-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0003_producerepr_label_recyclerepr_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoffer',
            name='blocked_credit',
            field=models.FloatField(default=0.0),
        ),
    ]
