# Generated by Django 5.1.6 on 2025-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0004_countercreditoffer_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(editable=False, max_length=8),
        ),
    ]
