# Generated by Django 5.1.6 on 2025-03-08 04:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0004_alter_producerepr_epr_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclerepr',
            name='epr_certificate',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
