# Generated by Django 5.1.6 on 2025-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0004_creditoffer_blocked_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprtarget',
            name='blocked_target',
            field=models.FloatField(default=0.0),
        ),
    ]
