# Generated by Django 5.1.6 on 2025-05-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0005_eprtarget_blocked_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countercreditoffer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='price_per_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
