# Generated by Django 5.1.6 on 2025-06-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0005_alter_transaction_order_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eprtarget',
            constraint=models.UniqueConstraint(fields=('producer', 'product_type', 'FY'), name='unique_producer_product_type_fy'),
        ),
    ]
