# Generated by Django 5.1.6 on 2025-03-08 07:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0006_alter_recyclerepr_epr_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerepr',
            name='epr_certificate',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
