# Generated by Django 5.1.6 on 2025-07-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0006_eprtarget_unique_producer_product_type_fy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
    ]
