# Generated by Django 5.1.6 on 2025-05-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0007_alter_countercreditoffer_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countercreditoffer',
            name='offer_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='countercreditoffer',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='blocked_credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='credit_available',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='minimum_purchase',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='price_per_credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eprcredit',
            name='available_certificate_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eprcredit',
            name='comulative_certificate_potential',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eprtarget',
            name='blocked_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchasesrequest',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_per_credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
