# Generated by Django 5.1.6 on 2025-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0008_alter_countercreditoffer_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprcredit',
            name='current_processing',
            field=models.FloatField(default=0.0),
        ),
    ]
