# Generated by Django 5.1.6 on 2025-03-08 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0008_alter_producerepr_epr_certificate'),
        ('users', '0003_alter_producer_company_logo_alter_producer_pcb_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPRTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('product_type', models.CharField(max_length=100)),
                ('credit_type', models.CharField(max_length=100)),
                ('FY', models.IntegerField()),
                ('target_quantity', models.IntegerField()),
                ('epr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_accounts', to='epr_account.producerepr')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='users.producer')),
            ],
        ),
    ]
