# Generated by Django 5.1.6 on 2025-03-09 12:34

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0009_eprtarget'),
        ('users', '0004_alter_producer_pcb_doc_alter_recycler_pcb_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprcredit',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_credits', to='users.recycler'),
        ),
        migrations.AlterField(
            model_name='eprtarget',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_targets', to='users.producer'),
        ),
        migrations.CreateModel(
            name='CreditOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epr_registration_number', models.CharField(max_length=50)),
                ('FY', models.IntegerField()),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('E-waste', 'E-waste'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Oil', 'Oil')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('offer_title', models.CharField()),
                ('credit_available', models.FloatField()),
                ('minimum_purchase', models.FloatField()),
                ('price_per_credit', models.FloatField()),
                ('documents', cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw')),
                ('epr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_offers', to='epr_account.recyclerepr')),
                ('epr_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_credits', to='epr_account.eprcredit')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_offers', to='users.recycler')),
            ],
        ),
        migrations.CreateModel(
            name='CounterCreditOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='users.producer')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_credit_offers', to='users.recycler')),
                ('credit_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_credit_offers', to='epr_account.creditoffer')),
            ],
        ),
    ]
