# Generated by Django 5.1.6 on 2025-05-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0009_eprcredit_current_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='epr_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epr_account.eprtarget'),
        ),
    ]
