# Generated by Django 5.1.6 on 2025-03-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0010_alter_eprcredit_recycler_alter_eprtarget_producer_and_more'),
        ('users', '0004_alter_producer_pcb_doc_alter_recycler_pcb_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countercreditoffer',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_counter_credit_offer', to='users.producer'),
        ),
        migrations.AlterField(
            model_name='countercreditoffer',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_counter_credit_offers', to='users.recycler'),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_credit_offers', to='epr_account.recyclerepr'),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='epr_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_credit_offers', to='epr_account.eprcredit'),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_credit_offers', to='users.recycler'),
        ),
        migrations.AlterField(
            model_name='eprcredit',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_credits', to='epr_account.recyclerepr'),
        ),
        migrations.AlterField(
            model_name='eprcredit',
            name='recycler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_epr_credits', to='users.recycler'),
        ),
        migrations.AlterField(
            model_name='eprtarget',
            name='epr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_account_targets', to='epr_account.producerepr'),
        ),
        migrations.AlterField(
            model_name='eprtarget',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_epr_targets', to='users.producer'),
        ),
    ]
