# Generated by Django 5.1.6 on 2025-05-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0010_transaction_epr_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='epr_account.creditoffer'),
        ),
    ]
