# Generated by Django 5.1.6 on 2025-03-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0011_alter_countercreditoffer_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoffer',
            name='offer_title',
            field=models.CharField(max_length=255),
        ),
    ]
