# Generated by Django 5.1.6 on 2025-03-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0012_alter_creditoffer_offer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='countercreditoffer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countercreditoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
