# Generated by Django 5.1.6 on 2025-03-12 05:20

import cloudinary.models
import django.core.validators
import epr_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0013_countercreditoffer_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoffer',
            name='documents',
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='availability_proof',
            field=cloudinary.models.CloudinaryField(default=['Tax Invoice', 'E-wayBIll', 'Loading slip', 'Lorry Receipt copy', 'Recycling Certificate Copy'], max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='supporting_docs',
            field=models.JSONField(default=list, validators=[django.core.validators.MinLengthValidator(5), epr_account.models.validate_doc_choices]),
        ),
    ]
