# Generated by Django 5.1.6 on 2025-03-12 07:47

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import epr_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0014_remove_creditoffer_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoffer',
            name='supporting_docs',
        ),
        migrations.AddField(
            model_name='countercreditoffer',
            name='producer_epr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='counter_credit_offers', to='epr_account.producerepr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditoffer',
            name='supporting_doc',
            field=models.JSONField(default=epr_account.models.get_default_supporting_docs, validators=[django.core.validators.MinLengthValidator(5), epr_account.models.validate_doc_choices]),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='FY',
            field=models.IntegerField(default=epr_account.models.get_default_year),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='availability_proof',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='credit_available',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='minimum_purchase',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='offer_title',
            field=models.CharField(default='Default Offer', max_length=255),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='price_per_credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
