# Generated by Django 5.1.6 on 2025-03-14 11:46

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0015_remove_creditoffer_supporting_docs_and_more'),
        ('users', '0006_producer_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('total_price', models.FloatField()),
                ('credit_type', models.CharField(max_length=100)),
                ('price_per_credit', models.FloatField()),
                ('product_type', models.CharField(max_length=100)),
                ('producer_type', models.CharField(max_length=100)),
                ('credit_quantity', models.FloatField()),
                ('offered_by', models.CharField(max_length=20)),
                ('work_order_date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('transaction_proof', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('counter_credit_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epr_account.countercreditoffer')),
                ('credit_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epr_account.creditoffer')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_transactions', to='users.producer')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_transactions', to='users.recycler')),
            ],
        ),
    ]
