# Generated by Django 5.1.6 on 2025-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0018_remove_creditoffer_supporting_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerepr',
            name='epr_registered_name',
            field=models.CharField(default='registered name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recyclerepr',
            name='epr_registered_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
