# Generated by Django 5.1.6 on 2025-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0019_producerepr_epr_registered_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recycler_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='waste_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
