# Generated by Django 5.1.6 on 2025-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0020_transaction_recycler_type_transaction_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprcredit',
            name='available_certificate_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eprcredit',
            name='comulative_certificate_potential',
            field=models.FloatField(),
        ),
    ]
