# Generated by Django 5.1.6 on 2025-03-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0021_alter_eprcredit_available_certificate_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='producer_epr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epr_transactions', to='epr_account.producerepr'),
        ),
    ]
