# Generated by Django 5.1.6 on 2025-03-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0022_transaction_producer_epr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='producer_epr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_transactions', to='epr_account.producerepr'),
        ),
    ]
