# Generated by Django 5.1.6 on 2025-03-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0023_alter_transaction_producer_epr'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='producer_epr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epr_transactions', to='epr_account.producerepr'),
        ),
        migrations.CreateModel(
            name='RecyclerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_types', to='epr_account.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='epr_account.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_types', to='epr_account.wastetype')),
            ],
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_types', to='epr_account.wastetype')),
            ],
        ),
    ]
