# Generated by Django 5.1.6 on 2025-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0024_wastetype_alter_transaction_producer_epr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprtarget',
            name='achieved_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eprtarget',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
