# Generated by Django 5.1.6 on 2025-03-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0025_eprtarget_achieved_quantity_eprtarget_is_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoffer',
            name='credit_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
