# Generated by Django 5.1.6 on 2025-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0027_remove_producerepr_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprtarget',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
