# Generated by Django 5.1.6 on 2025-03-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0028_eprtarget_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerepr',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='recyclerepr',
            name='company_name',
        ),
    ]
