# Generated by Django 5.1.6 on 2025-03-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0029_remove_producerepr_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recycle_unique_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
