# Generated by Django 5.1.6 on 2025-03-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0030_transaction_recycle_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recycle_unique_id',
        ),
    ]
