# Generated by Django 5.1.6 on 2025-03-21 07:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0031_remove_transaction_recycle_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trail_documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='trail_documents'),
        ),
    ]
