# Generated by Django 5.1.6 on 2025-03-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0033_producerepr_is_approved_recyclerepr_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerepr',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='recyclerepr',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
