# Generated by Django 5.1.6 on 2025-03-25 17:46

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0036_countercreditoffer_created_at_creditoffer_created_at_and_more'),
        ('users', '0010_alter_producer_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='producer_transfer_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='producer_transfer_proof'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recycler_transfer_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='recycler_transfer_proof'),
        ),
        migrations.CreateModel(
            name='PurchasesRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('credit_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='epr_account.creditoffer')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_producer_transactions', to='users.producer')),
                ('producer_epr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_epr_transactions', to='epr_account.producerepr')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_recycler_transactions', to='users.recycler')),
            ],
        ),
    ]
