# Generated by Django 5.1.6 on 2025-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0037_transaction_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoffer',
            name='credit_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='creditoffer',
            name='product_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='eprcredit',
            name='credit_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='eprcredit',
            name='product_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='eprtarget',
            name='credit_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='eprtarget',
            name='product_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='producerepr',
            name='epr_registered_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producerepr',
            name='producer_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='recyclerepr',
            name='recycler_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='producer_type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_type',
            field=models.CharField(),
        ),
    ]
