# Generated by Django 5.1.6 on 2025-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0038_alter_creditoffer_credit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclerepr',
            name='epr_registered_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recycler_type',
            field=models.CharField(),
        ),
    ]
