# Generated by Django 5.1.6 on 2025-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0039_alter_recyclerepr_epr_registered_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countercreditoffer',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesrequest',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
