# Generated by Django 5.1.6 on 2025-03-28 10:28

import epr_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0040_countercreditoffer_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countercreditoffer',
            name='FY',
            field=models.IntegerField(default=epr_account.models.get_default_year),
        ),
        migrations.AddField(
            model_name='purchasesrequest',
            name='FY',
            field=models.IntegerField(default=epr_account.models.get_default_year),
        ),
    ]
