# Generated by Django 5.1.6 on 2025-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0041_countercreditoffer_fy_purchasesrequest_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesrequest',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
