# Generated by Django 5.1.6 on 2025-04-01 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr_account', '0042_purchasesrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
